language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly


before_script:
  - pecl install pcov
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo
  - composer config minimum-stability ${STABILITY}
  - COMPOSER_MEMORY_LIMIT=-1 composer install
  - vendor/bin/pcov clobber
# - wget http://getcomposer.org/composer.phar
#  - php composer.phar require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source

script:
  - mkdir -p build/logs
  # run tests in random order to expose hidden inter-test dependencies (by breakages)
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls --exclude-no-stmt

after_success:
  - coveralls
env: # important!
  - STABILITY=stable
  - STABILITY=dev
matrix:
  allow_failures:
  - php: nightly
  
#notifications:
#  webhooks:
#    urls:
#      # Send Hall Dev Loung a Message
#      - secure: "XgvziuMTeNM3DKo5VY6VQeIZyhuoNxtHBezXWpsy5eEqcEyciAOodTeW4La5kckEyu2MYC2r7Vek9jv9rshyyhP74NNugVJPt7OZeBtmjILvwjsUk+VJP6xzK+zxC3Xo57PxlSo4O8OMNJ3Is8Sc+6AJ9tbgx4KFkE2u3f3j/n8="
#    on_start: true 
