language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install
#  - wget http://getcomposer.org/composer.phar
#  - php composer.phar require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls --exclude-no-stmt

#notifications:
#  webhooks:
#    urls:
#      # Send Hall Dev Loung a Message
#      - secure: "XgvziuMTeNM3DKo5VY6VQeIZyhuoNxtHBezXWpsy5eEqcEyciAOodTeW4La5kckEyu2MYC2r7Vek9jv9rshyyhP74NNugVJPt7OZeBtmjILvwjsUk+VJP6xzK+zxC3Xo57PxlSo4O8OMNJ3Is8Sc+6AJ9tbgx4KFkE2u3f3j/n8="
#    on_start: true