name: Commit Tag

on:
  workflow_dispatch:
    inputs:
      tag-value:
        required: true
      dry-run:
        type: boolean
        description: should this be done as a dry run.
        default: true
      prefix-v:
        type: boolean
        description: should a v be appended to start of tag.
        default: false
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: ./.github/actions/tag_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: ${{ github.event.inputs.prefix-v }}
          DRY_RUN: ${{ github.event.inputs.dry-run }}
          CUSTOM_TAG: ${{ github.event.inputs.tag-value }}